Fix ping_node issue (#174)
* Fix ping_node issue

this patch fix following error when calling port.ping_node('ip')

ttributeError: 'VNXConnectionPort' does not contain attribute
'ping_node'

* Fix pep8 issue after upgrading pyflakes

pep8 build failed due to pyflakes v1.6.0